spring:
  devtools:
    restart:
      trigger-file: 'trigger.txt'
      enabled: true
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1
        deny: 192.168.2.1
        login-username: admin
        login-password: 50a9eeb08ddfb72b
        reset-enable: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

